version: '3.3'

services:
  backend:
    env_file:
      - "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "artinrezaee/geoip-backend"
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "artinrezaee/geoip-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend:be"